# Generated by Django 5.1 on 2025-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phonenumber', models.CharField(help_text='Local phone number', max_length=11, verbose_name='Phone number 1')),
                ('Phonenumber2', models.CharField(blank=True, help_text='Other phone number, if any', max_length=20, verbose_name='Phone number 2')),
                ('Address', models.TextField(blank=True, max_length=200, verbose_name='Home Address')),
            ],
        ),
    ]
