# Generated by Django 5.1 on 2025-04-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text='First name', max_length=200, null=True)),
                ('LastName', models.CharField(help_text='Last name', max_length=200, null=True)),
                ('DateofBirth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('Passportphoto', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('DateofEntry', models.DateField(null=True, verbose_name='Date of Entry')),
                ('DateofExit', models.DateField(blank=True, null=True, verbose_name='Date of Exit')),
                ('DateofGraduation', models.DateField(blank=True, null=True, verbose_name='Date of Graduation')),
                ('Grade', models.ManyToManyField(related_name='profile', to='results.grade', verbose_name='Grade at entry')),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='parents.parent')),
                ('sessions', models.ManyToManyField(related_name='profile', to='results.session', verbose_name='Present Session')),
                ('term', models.ManyToManyField(related_name='profile', to='results.term', verbose_name='Term')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(help_text='Phone number', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
