# Generated by Django 5.1 on 2025-04-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfSubject', models.CharField(max_length=20, verbose_name='Subject')),
                ('FirstCA', models.FloatField(default=0, help_text='CA 1', verbose_name='1st Continuous Assessment (15%)')),
                ('SecondCA', models.FloatField(default=0, help_text='CA 2', verbose_name='2nd Continuous Assessment (15%)')),
                ('Exam', models.FloatField(default=0, help_text='Exam Score', verbose_name='Exam (70%)')),
                ('total', models.FloatField(default=0, verbose_name='Total (100%)')),
                ('Grade', models.ManyToManyField(to='results.grade', verbose_name='Grades')),
                ('Term', models.ManyToManyField(to='results.term', verbose_name='Term')),
                ('sesssion', models.ManyToManyField(to='results.session', verbose_name='Session')),
                ('students', models.ManyToManyField(related_name='students', to='student.students_file')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ca', models.FloatField(default=0, verbose_name='First CA')),
                ('second_ca', models.FloatField(default=0, verbose_name='Second CA')),
                ('exam', models.FloatField(default=0, verbose_name='Exam')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='results.grade')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='results.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.students_file')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='results.term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ca', models.FloatField(default=0, verbose_name='First CA')),
                ('second_ca', models.FloatField(default=0, verbose_name='Second CA')),
                ('exam', models.FloatField(default=0, verbose_name='Exam')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student.students_file')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='subjects.subject')),
            ],
        ),
    ]
