# Generated by Django 5.1 on 2025-04-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='FirstCA',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='SecondCA',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total',
        ),
    ]
