# Generated by Django 5.1 on 2025-05-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_exam_remove_subject_firstca_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreTable',
        ),
    ]
